title: Websites for Dissent
description: Free websites for grassroots groups
url: https://joe.irving.me.uk

# Social & contact
telegram: chaoscake
email: joe@irving.me.uk

background_color: "#000000"
accent_color: "#CD00CD"

permalink: /:categories/:title/
collections:
  posts:
    permalink: /posts/:categories/:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-linkpreview
