title: Websites for Dissent
description: Free (ish) websites for grassroots groups

email: joe@irving.me.uk
url: https://joe.irving.me.uk
telegram: chaoscake

background_color: "rgb(171,32,253)"
accent_color: red

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-linkpreview

sass:
    sass_dir: _sass
